// DO NOT EDIT — generated by scripts/generate-monitor-targets.mjs
// Run: node scripts/generate-monitor-targets.mjs

export const GENERATED_TARGETS = [
  { id: "prime-self.health", url: "https://api.selfprime.net/health", contains: "ok" },
  { id: "schedule-worker.health", url: "https://schedule.latwoodtech.work/health", contains: "ok" },
  { id: "video-cron.health", url: "https://video-cron.latwoodtech.work/health", contains: "ok" },
  { id: "status-prober.health", url: "https://status.latwoodtech.work/health", contains: "ok" },
  { id: "admin-studio-staging.health", url: "https://api.admin.latimerwoods.dev/health", contains: "ok" },
  { id: "capricast-api-staging.health", url: "https://api.capricast.latimerwoods.dev/health", contains: "ok" },
  { id: "capricast-api.health", url: "https://api.capricast.com/health", contains: "ok" },
  { id: "cypher-healing.health", url: "https://api.cipherofhealing.com/health", contains: "ok" },
  { id: "coh.health", url: "https://api.cypherofhealing.com/health", contains: "ok" },
  { id: "factory-cross-repo.health", url: "https://factory-cross-repo.latwoodtech.work/health", contains: "ok" },
  { id: "factory-agent-gateway.health", url: "https://factory-agent-gateway.adrper79.workers.dev/health", contains: "ok" },
  { id: "factory-supervisor.health", url: "https://supervisor.latwoodtech.work/health", contains: "ok" },
  { id: "lead-gen.health", url: "https://lead-gen.adrper79.workers.dev/health", contains: "ok" },
  { id: "factory-core-api.health", url: "https://core.latwoodtech.work/health", contains: "ok" },
  { id: "webhook-fanout.health", url: "https://webhooks.latwoodtech.work/stripe/health", contains: "ok" },
  { id: "daily-brief.health", url: "https://dbrief.latwoodtech.work/health", contains: "ok" },
  { id: "xico-city.health", url: "https://xicocity.com/health", contains: "ok" },
  { id: "xico-city-staging.health", url: "https://staging.xicocity.com/health", contains: "ok" },
  { id: "qa-tools-worker.health", url: "https://api.qa.latimerwoods.dev/health", contains: "ok" },
  { id: "marketing-supervisor.health", url: "https://marketing-supervisor.adrper79.workers.dev/health", contains: "ok" },
  { id: "marketing-supervisor-staging.health", url: "https://marketing-supervisor-staging.adrper79.workers.dev/health", contains: "ok" },
  { id: "referrals.health", url: "https://referrals.adrper79.workers.dev/health", contains: "ok" },
  { id: "llm-rank-worker.health", url: "https://llm-rank-worker.adrper79.workers.dev/health", contains: "ok" },
] as const;
